post/post/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('postapp.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/postapp/urls.py
from django.urls import include, path
from . import views
from .views import post

urlpatterns = [ 
    path('newPost', views.newPostView, name='newPost'), #Page for making a new post
    path('<int:pk>/', views.postDetailView.as_view(), name='post_detail'), # specific post
    path('delete/<int:nid>', views.delete_view, name = 'post_delete'), #to delete a  post
    path('', views.index_view, name='post_index'),
    path('feed', views.feed_view, name='feed'),
    path('newPost/', views.newPostView, name='newPost'),
    path('<int:pk>/add_comment/', views.add_comment_view, name='add_comment'),
     path('delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

post/postapp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings


alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', '') #Just in case 

class post(models.Model):
    #login profile
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True) #Needs improvement, compare to others
    description = models.TextField()
    created_at = models.DateTimeField(auto_now = True) #Simple enough
    updated_at = models.DateTimeField(auto_now=True) 
    treats = models.IntegerField(default=0) #our 'likes' counter. must start at 0
    # image = models.ImageField(upload_to='uploads/')
    image=models.ImageField(upload_to='img')


    def __str__(self):
      #just needed to add this lil format thing here
      return "{}".format(self.id)
    # class Meta:
    #     indexes= [models.Index(fields=['id'])]

class Comment(models.Model):
    post = models.ForeignKey(post, on_delete=models.CASCADE, related_name='comments', default=1)  # Provide a default value
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

post/postapp/forms.py
from django import forms
from .models import post
from .models import *
from django.db import models

class addPostForm(forms.ModelForm):
  class Meta:
    #The form for creating a new post
    model = post
    fields = ['image', 'description']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

post/postapp/views.py
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect 
from django.shortcuts import render, redirect 
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView, ListView, DetailView
from .forms import addPostForm
from django.shortcuts import (get_object_or_404, render, redirect)
from .models import post, Comment
from django.contrib.auth.decorators import login_required
from django.conf import settings
User = settings.AUTH_USER_MODEL
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm
from django.core.files.base import ContentFile
import os
from django.core.files.storage import default_storage
from django.http import JsonResponse

@login_required
def newPostView(request):
  context = {}
  #Your mystery field was actually the image not uploading
  #just needed request.FILES adding in
  form = addPostForm(request.POST, request.FILES or None)
  if(request.method == 'POST'):
    if form.is_valid():
      #user wasnt being saved properly either 
      #gets values from form
      post = form.save(commit=False)
      #assigns current user as author
      post.author = request.user
      #saves post
      post.save()
      messages.add_message(request, messages.SUCCESS, 'Post Created')
      return redirect('post_index')
    else:
      messages.add_message(request, messages.ERROR, 'Invalid form data; post not created')
  context['form'] = form
  return render(request, "post/newpostpage.html", context)


class postDetailView(DetailView):
    model = post
    template_name = 'post/postdetail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = self.get_object()
            comment.save()
            return redirect('post_detail', pk=self.kwargs['pk'])
        else:
            return redirect('post_detail', pk=self.kwargs['pk'])

def delete_comment(request, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        comment.delete()
        return JsonResponse({'success': True})
    except Comment.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Comment does not exist'})

@login_required
def index_view(request): 
    context = {} 
    # Get all posts
    if request.user.is_staff:
        all_posts = post.objects.all()
    else:
        all_posts = post.objects.filter(author=request.user)
    # Filter out posts without a valid image
    valid_posts = []
    for post_item in all_posts:
        if post_item.image and default_storage.exists(post_item.image.name):
            valid_posts.append(post_item)
    context["post_list"] = valid_posts
    return render(request, "post/postIndex.html", context)

def feed_view(request):
  all_posts = sorted(post.objects.all(), key=lambda p:(p.created_at), reverse=True)
  valid_posts = []
  for post_item in all_posts:
      if post_item.image and default_storage.exists(post_item.image.name):
          valid_posts.append(post_item)
  return render(request, "post/postIndex.html", {'post_list':valid_posts})

@login_required
def delete_view(request, nid):
  obj= get_object_or_404(post, id=nid)
  if(obj.author != request.user and not(is_admin(request.user))):
    raise PermissionDenied()
  obj.delete()
  messages.add_message(request, messages.SUCCESS, 'Post Deleted')
  return redirect('post_index')

@login_required
def add_comment_view(request, pk):
    post_object = get_object_or_404(post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post_object
            comment.save()
            return redirect('post_detail', pk=pk)
    else:
        form = CommentForm()
    # Redirect to post detail page
    return redirect('post_detail', pk=pk)  

post/postapp/templates/post/newpostpage.html
{% extends 'base.html' %}
{% block content %}       
 <!--i changed some spacing here becuase it was confusing me  -->
<form method = 'post' enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button type ="submit">Upload</button>
</form>

{% endblock content %}

post/postapp/templates/post/postIndex.html
{% extends 'base.html' %}
{% block content %}
    <h1>Post List</h1>
        {% for post in post_list|slice:"0:20" %}
        <div class="post-container">
            <div class="post-box">
                <div class="post-details-box">
                    <h2 class="author">{{ post.author }}</h2>
                    <a href="http://localhost:8002/post/{{ post.id }}">
                    <img src="{{ post.image.url }}" alt="Post Image" class="max-image-size-details">
                </a>
                    <p>{{ post.created_at }}</p>
                    <p class="post-title">{{ post.description }}</p>
                    <div class="treats-section">
                        <p>Treats: <span id="treats-count">{{ post.treats }}</span></p>
                        <button id="add-treat-btn">Give Treat</button>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#add-treat-btn').click(function() {
                    var treatsCount = parseInt($('#treats-count').text());
                    treatsCount++;
                    $('#treats-count').text(treatsCount);
                });
            });
        </script>
        {% endfor %}
{% endblock content %}

post/postapp/templates/post/postdetail.html
{% extends 'base.html' %}
{% block content %}
    <div class="post-container">
        <div class="post-box">
            <div class="post-details-box">
                <h2 class="author">{{ post.author }}</h2>
                <img src="{{ post.image.url }}" alt="Post Image" class="max-image-size-details">
                <p class="post-title">{{ post.description }}</p>
                <div class="treats-section">
                    <p>Treats: <span id="treats-count">{{ post.treats }}</span></p>
                    <button id="add-treat-btn">Give Treat</button>
                </div>
            </div>
        </div>
        <div class="comments-box" id="comments-box">
            <h4>Comments</h4>
            <ul>
                {% for comment in post.comments.all %}
                    <li id="comment-{{ comment.id }}">
                        <div class="comment">
                            <p class="comment-user">{{ comment.author }}</p>
                            <p class="comment-content">{{ comment.content }}</p>
                            <p class="comment-date">{{ comment.created_at }}</p>
                            {% if user.is_authenticated and user == comment.author %}
                            <form id="delete-comment-{{ comment.id }}" class="delete-comment-form" data-comment-id="{{ comment.id }}" method="post" action="{% url 'delete_comment' comment.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="delete-comment-btn smaller">Delete</button>
                                </form>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <form method="post" action="{% url 'add_comment' post.id %}">
                {% csrf_token %}
                <div>
                    <textarea id="id_content" name="content" placeholder="Add a comment..." maxlength="100"></textarea>
                </div>
                <div>
                    <button type="submit">Add Comment</button>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#add-treat-btn').click(function() {
                var treatsCount = parseInt($('#treats-count').text());
                treatsCount++;
                $('#treats-count').text(treatsCount);
            });

            var input = $('#id_content');
            input.on('input', function() {
                this.classList.remove('expanding');
                this.style.height = '1.5em'; /* Set initial height */
                this.style.height = (this.scrollHeight) + 'px'; /* Expand to fit content */
            });

            $('.delete-comment-form').submit(function(e) {
                e.preventDefault();
                var commentId = $(this).data('comment-id');
                var deleteUrl = $(this).attr('action');
                $.ajax({
                    url: deleteUrl,
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function() {
                        $('#comment-' + commentId).remove(); // Remove the comment from the DOM
                    }
                });
            });
        });
    </script>
{% endblock content %}